select 'EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '' '', '''+(Nombres+' '+Apellidos)+'''' from Alumno

SELECT * FROM Vw_Vista_Clase_Para_Alumnos order by NombreHorario


EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Nayara Atikigua'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Ambar Zoe'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Luz Cuyen'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Damaris Xiomara'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Amin Mihair'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Ashley Roxana'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '131-21', 'Maia Shasman'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Giulianna Adel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Máxima Cielo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Delfina Maite'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Renata Reina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Braiton Nicolas'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Agustina Jeraldine'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1491-15', 'Umma Magaly'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Josua '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Casiano Gael'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Joaquin Cristiano'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Tania Azul'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Ahsley '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Georgiy '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '241-31', 'Gael Anacleto'


EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Gina Noelia'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Miah Malena'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Julieta Ainhoa'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Josefina Antonella'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Aliss Cristina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '681-12', 'Cain Lihuen'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Bianca Daniela'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Maia '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Lisbet Yanina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Marisa Esmeralda'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Quilla Aneley'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Pablo Santiago'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Celeste Miguelina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Fatima Luisana'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Ximena Lucia'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Natasha Liz'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Bruno Cristian'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '831-24', 'Abigail Delfina'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Paulo Valentino'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Ma. Daniela'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Sherazade Ihomara'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Marimar Ana'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Facundo Socrates'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Xiomara Maylin'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Melani Daniela'


EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Rodrigo Eliazar'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Alcides Angelo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Helene Noemi'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Juan Galo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Gimena Carlina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Alexander Cristiano'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'India Rosario'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Mishel Nicol'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Estrellita Aline'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Alexia Mel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Iara Emelin'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Abrahan Gaston'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Roman Felix'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Donatto Lorenzo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Arwen Melody'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Britany Esperanza'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Eithan Uzziel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Malvina Nahomi'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Dario Yutiel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Elisa Micaela'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Milton Oscar'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Izan Benicio'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Felipe Guido'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Melina Shirley'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Daialen Yoselin'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Amir Azael'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Pedro Renan'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Francesca Yocelyn'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Dillan '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Thian Yair'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Aitiana Delfina'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Erica Malena'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Jana Juanita'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Vera Tatiana'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Teo Facundo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Mara Evelyn'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Genesis Angela'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Gianlucca Isaias'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Franco Rodrigo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Tomas Yahir'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Lucio Leandro'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Anna Franccesca'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Isabela Aylen'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1272-32', 'Bastian Liam'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Karen Elsa'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Nerea Camila'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Walter Jaciel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Yazmin Maiten'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Yamila Ailin'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Luna Ivonne'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Adabel Ayala'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Felipe Bernabeth'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Danna Liwen'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Benicio Tiziano'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Genesis Milagros'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '352-11', 'Valentin Sebastian'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Constantino Manuel'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Solange Costanza'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Ian Efrain'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Morena Miranda'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Ana Sol'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Bianca Yasmine'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Lujan Alexia'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Guila Ruth'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Lenny Amin'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Maite Leila'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Joscelyn Agustina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Ignacio Raul'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '462-21', 'Elvis Hector'

EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Katia Delfina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Tania Tomasa'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Lourdes Carlina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Victoria Lorenza'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Bruno Francisco'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Elena Amarilis'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Francisco Clayton'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Gabriela Melody'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Julia Danielle'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Daniel Demir'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Amaralina '
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Eliseo Josue'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Maite Evangelina'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '572-31', 'Bautista Joshua'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Joselin Diamela'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Sohee Marilyn'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Giovanna Desiree'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1162-25', 'Xavier Lorenzo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '1052-12', 'Benjamin Amadeo'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Antonella Paloma'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '791-13', 'Briana Princesa'
EXECUTE [dbo].[Sp_Registrar_Alumno_en_Clase] '941-33', 'Neylan Dilara'
SELECT * FROM Vw_Vista_Clase_Para_Alumnos

SELECT * FROM MateriaHorarioProfesorAlumno;


SELECT * FROM Asistencia